// library.js - Biblioteca de Nebulaudio
// Última actualización: 22 de enero de 2026

const LIBRARY = [
  {
    "id": "bastian",
    "title": "Bastián",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Cinematográfico",
    "style_decade": "2020s",
    "ambience": "Recuerdo",
    "mood": "Melancólico",
    "duration": 68,
    "audio_folder": "audios",
    "pdf_folder": "pdf",
    "file_mp3": "bastian.mp3",
    "file_pdf": "bastian.pdf",
    "downloads": 12
  },
  {
    "id": "carabobo-22",
    "title": "Carabobo-22",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Folclórico",
    "style_decade": "1970s",
    "ambience": "Campo",
    "mood": "Contemplativo",
    "duration": 74,
    "audio_folder": "audios",
    "pdf_folder": "pdf",
    "file_mp3": "carabobo-22.mp3",
    "file_pdf": "carabobo-22.pdf",
    "downloads": 8
  },
  {
    "id": "cotidiana",
    "title": "Cotidiana",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Urbano",
    "style_decade": "2020s",
    "ambience": "Ciudad",
    "mood": "Nostálgico",
    "duration": 52,
    "audio_folder": "audios",
    "pdf_folder": "pdf",
    "file_mp3": "cotidiana.mp3",
    "file_pdf": "cotidiana.pdf",
    "downloads": 21
  },
  {
    "id": "desolacion",
    "title": "Desolación",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Cinematográfico",
    "style_decade": "2020s",
    "ambience": "Espacio",
    "mood": "Melancólico",
    "duration": 81,
    "audio_folder": "audios",
    "pdf_folder": "pdf",
    "file_mp3": "desolacion.mp3",
    "file_pdf": "desolacion.pdf",
    "downloads": 17
  },
  {
    "id": "el-espacio-de-los-juguetes",
    "title": "El Espacio de los Juguetes",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Íntimo",
    "style_decade": "1990s",
    "ambience": "Recuerdo",
    "mood": "Contemplativo",
    "duration": 63,
    "audio_folder": "audios",
    "pdf_folder": "pdf",
    "file_mp3": "el-espacio-de-los-juguetes.mp3",
    "file_pdf": "el-espacio-de-los-juguetes.pdf",
    "downloads": 5
  },
  {
    "id": "el-infeliz",
    "title": "El Infeliz",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Cinematográfico",
    "style_decade": "2020s",
    "ambience": "Espacio",
    "mood": "Misterioso",
    "duration": 77,
    "audio_folder": "audios",
    "pdf_folder": "pdf",
    "file_mp3": "el-infeliz.mp3",
    "file_pdf": "el-infeliz.pdf",
    "downloads": 9
  },
  {
    "id": "el-paseo",
    "title": "El Paseo",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Urbano",
    "style_decade": "2020s",
    "ambience": "Ciudad",
    "mood": "Tranquilo",
    "duration": 58,
    "audio_folder": "audios",
    "pdf_folder": "pdf",
    "file_mp3": "el-paseo.mp3",
    "file_pdf": "el-paseo.pdf",
    "downloads": 14
  },
  {
    "id": "entre-suenos-y-fantasias",
    "title": "Entre Sueños y Fantasías",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Íntimo",
    "style_decade": "2010s",
    "ambience": "Recuerdo",
    "mood": "Esperanzador",
    "duration": 72,
    "audio_folder": "audios",
    "pdf_folder": "pdf",
    "file_mp3": "entre-suenos-y-fantasias.mp3",
    "file_pdf": "entre-suenos-y-fantasias.pdf",
    "downloads": 3
  },
  {
    "id": "escalones",
    "title": "Escalones",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Cinematográfico",
    "style_decade": "2020s",
    "ambience": "Ciudad",
    "mood": "Contemplativo",
    "duration": 66,
    "audio_folder": "audios",
    "pdf_folder": "pdf",
    "file_mp3": "escalones.mp3",
    "file_pdf": "escalones.pdf",
    "downloads": 11
  },
  {
    "id": "humbolt",
    "title": "Humbolt",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Cinematográfico",
    "style_decade": "2020s",
    "ambience": "Montaña",
    "mood": "Contemplativo",
    "duration": 79,
    "audio_folder": "audios",
    "pdf_folder": "pdf",
    "file_mp3": "humbolt.mp3",
    "file_pdf": "humbolt.pdf",
    "downloads": 7
  },
  {
    "id": "karim",
    "title": "Karím",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Íntimo",
    "style_decade": "2020s",
    "ambience": "Recuerdo",
    "mood": "Nostálgico",
    "duration": 64,
    "audio_folder": "audio",
    "pdf_folder": "pdf",
    "file_mp3": "karim.mp3",
    "file_pdf": "karim.pdf",
    "downloads": 6
  },
  {
    "id": "kraloka",
    "title": "Kraloka",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Cinematográfico",
    "style_decade": "2020s",
    "ambience": "Espacio",
    "mood": "Épico",
    "duration": 85,
    "audio_folder": "audio",
    "pdf_folder": "pdf",
    "file_mp3": "kraloka.mp3",
    "file_pdf": "kraloka.pdf",
    "downloads": 24
  },
  {
    "id": "navio",
    "title": "Navío",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Cinematográfico",
    "style_decade": "2020s",
    "ambience": "Playa",
    "mood": "Melancólico",
    "duration": 70,
    "audio_folder": "audio",
    "pdf_folder": "pdf",
    "file_mp3": "navio.mp3",
    "file_pdf": "navio.pdf",
    "downloads": 19
  },
  {
    "id": "peldaños",
    "title": "Peldaños",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Cinematográfico",
    "style_decade": "2020s",
    "ambience": "Ciudad",
    "mood": "Contemplativo",
    "duration": 61,
    "audio_folder": "audio",
    "pdf_folder": "pdf",
    "file_mp3": "peldaños.mp3",
    "file_pdf": "peldaños.pdf",
    "downloads": 10
  },
  {
    "id": "pesadumbre",
    "title": "Pesadumbre",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Cinematográfico",
    "style_decade": "2020s",
    "ambience": "Espacio",
    "mood": "Melancólico",
    "duration": 83,
    "audio_folder": "audio",
    "pdf_folder": "pdf",
    "file_mp3": "pesadumbre.mp3",
    "file_pdf": "pesadumbre.pdf",
    "downloads": 16
  },
  {
    "id": "pescando-soledades",
    "title": "Pescando Soledades",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Íntimo",
    "style_decade": "2020s",
    "ambience": "Playa",
    "mood": "Tranquilo",
    "duration": 76,
    "audio_folder": "audio",
    "pdf_folder": "pdf",
    "file_mp3": "pescando-soledades.mp3",
    "file_pdf": "pescando-soledades.pdf",
    "downloads": 4
  },
  {
    "id": "solemne",
    "title": "Solemne",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Cinematográfico",
    "style_decade": "2020s",
    "ambience": "Espacio",
    "mood": "Épico",
    "duration": 88,
    "audio_folder": "audio",
    "pdf_folder": "pdf",
    "file_mp3": "solemne.mp3",
    "file_pdf": "solemne.pdf",
    "downloads": 22
  },
  {
    "id": "sombra",
    "title": "Sombra",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Cinematográfico",
    "style_decade": "2020s",
    "ambience": "Ciudad",
    "mood": "Misterioso",
    "duration": 56,
    "audio_folder": "audio",
    "pdf_folder": "pdf",
    "file_mp3": "sombra.mp3",
    "file_pdf": "sombra.pdf",
    "downloads": 13
  },
  {
    "id": "valses-melancolicos",
    "title": "Valses Melancólicos",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Folclórico",
    "style_decade": "1930s",
    "ambience": "Café",
    "mood": "Melancólico",
    "duration": 82,
    "audio_folder": "audio",
    "pdf_folder": "pdf",
    "file_mp3": "valses-melancolicos.mp3",
    "file_pdf": "valses-melancolicos.pdf",
    "downloads": 18
  },
  // === NUEVAS PIEZAS ===
  {
    "id": "arte-ingenuo",
    "title": "Arte Ingenuo",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Íntimo",
    "style_decade": "2020s",
    "ambience": "Taller",
    "mood": "Inocente",
    "duration": 67,
    "audio_folder": "sonoras",
    "pdf_folder": "pdf",
    "file_mp3": "arte-ingenuo.mp3",
    "file_pdf": "arte-ingenuo.pdf",
    "downloads": 0
  },
  {
    "id": "beka",
    "title": "Beka",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Cinematográfico",
    "style_decade": "2020s",
    "ambience": "Recuerdo",
    "mood": "Nostálgico",
    "duration": 73,
    "audio_folder": "sonoras",
    "pdf_folder": "pdf",
    "file_mp3": "beka.mp3",
    "file_pdf": "beka.pdf",
    "downloads": 0
  },
  {
    "id": "besitos",
    "title": "Besitos",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Íntimo",
    "style_decade": "2010s",
    "ambience": "Hogar",
    "mood": "Cariñoso",
    "duration": 59,
    "audio_folder": "sonoras",
    "pdf_folder": "pdf",
    "file_mp3": "besitos.mp3",
    "file_pdf": "besitos.pdf",
    "downloads": 0
  },
  {
    "id": "calcceta",
    "title": "Calcceta",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Urbano",
    "style_decade": "2020s",
    "ambience": "Barrio",
    "mood": "Juguetón",
    "duration": 62,
    "audio_folder": "sonoras",
    "pdf_folder": "pdf",
    "file_mp3": "calcceta.mp3",
    "file_pdf": "calcceta.pdf",
    "downloads": 0
  },
  {
    "id": "chipi",
    "title": "Chipi",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Íntimo",
    "style_decade": "2020s",
    "ambience": "Infancia",
    "mood": "Alegre",
    "duration": 55,
    "audio_folder": "sonoras",
    "pdf_folder": "pdf",
    "file_mp3": "chipi.mp3",
    "file_pdf": "chipi.pdf",
    "downloads": 0
  },
  {
    "id": "cole",
    "title": "Cole",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Urbano",
    "style_decade": "2000s",
    "ambience": "Escuela",
    "mood": "Energético",
    "duration": 64,
    "audio_folder": "sonoras",
    "pdf_folder": "pdf",
    "file_mp3": "cole.mp3",
    "file_pdf": "cole.pdf",
    "downloads": 0
  },
  {
    "id": "edbe-oriente",
    "title": "Edbe Oriente",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Cinematográfico",
    "style_decade": "2020s",
    "ambience": "Ciudad",
    "mood": "Reflexivo",
    "duration": 78,
    "audio_folder": "sonoras",
    "pdf_folder": "pdf",
    "file_mp3": "edbe-oriente.mp3",
    "file_pdf": "edbe-oriente.pdf",
    "downloads": 0
  },
  {
    "id": "elevacion",
    "title": "Elevación",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Cinematográfico",
    "style_decade": "2020s",
    "ambience": "Espacio",
    "mood": "Esperanzador",
    "duration": 86,
    "audio_folder": "sonoras",
    "pdf_folder": "pdf",
    "file_mp3": "elevacion.mp3",
    "file_pdf": "elevacion.pdf",
    "downloads": 0
  },
  {
    "id": "gara",
    "title": "Gara",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Folclórico",
    "style_decade": "1970s",
    "ambience": "Llanos",
    "mood": "Contemplativo",
    "duration": 71,
    "audio_folder": "sonoras",
    "pdf_folder": "pdf",
    "file_mp3": "gara.mp3",
    "file_pdf": "gara.pdf",
    "downloads": 0
  },
  {
    "id": "kivanch",
    "title": "Kivanch",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Cinematográfico",
    "style_decade": "2020s",
    "ambience": "Desierto",
    "mood": "Misterioso",
    "duration": 80,
    "audio_folder": "sonoras",
    "pdf_folder": "pdf",
    "file_mp3": "kivanch.mp3",
    "file_pdf": "kivanch.pdf",
    "downloads": 0
  },
  {
    "id": "la-zuliana",
    "title": "La Zuliana",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Folclórico",
    "style_decade": "1960s",
    "ambience": "Lago",
    "mood": "Melancólico",
    "duration": 75,
    "audio_folder": "sonoras",
    "pdf_folder": "pdf",
    "file_mp3": "la-zuliana.mp3",
    "file_pdf": "la-zuliana.pdf",
    "downloads": 0
  },
  {
    "id": "linderos",
    "title": "Linderos",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Cinematográfico",
    "style_decade": "2020s",
    "ambience": "Frontera",
    "mood": "Contemplativo",
    "duration": 77,
    "audio_folder": "sonoraudio",
    "pdf_folder": "pdf",
    "file_mp3": "linderos.mp3",
    "file_pdf": "linderos.pdf",
    "downloads": 0
  },
  {
    "id": "los-artistas",
    "title": "Los Artistas",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Íntimo",
    "style_decade": "2010s",
    "ambience": "Taller",
    "mood": "Creativo",
    "duration": 69,
    "audio_folder": "sonoraudio",
    "pdf_folder": "pdf",
    "file_mp3": "los-artistas.mp3",
    "file_pdf": "los-artistas.pdf",
    "downloads": 0
  },
  {
    "id": "los-patacones-de-mi-ninez",
    "title": "Los Patácones de mi Niñez",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Folclórico",
    "style_decade": "1980s",
    "ambience": "Cocina",
    "mood": "Nostálgico",
    "duration": 72,
    "audio_folder": "sonoraudio",
    "pdf_folder": "pdf",
    "file_mp3": "los-patacones-de-mi-ninez.mp3",
    "file_pdf": "los-patacones-de-mi-ninez.pdf",
    "downloads": 0
  },
  {
    "id": "medano",
    "title": "Medaño",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Cinematográfico",
    "style_decade": "2020s",
    "ambience": "Desierto",
    "mood": "Solitario",
    "duration": 84,
    "audio_folder": "sonoraudio",
    "pdf_folder": "pdf",
    "file_mp3": "medano.mp3",
    "file_pdf": "medano.pdf",
    "downloads": 0
  },
  {
    "id": "nikoru",
    "title": "Nikoru",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Íntimo",
    "style_decade": "2020s",
    "ambience": "Bosque",
    "mood": "Tranquilo",
    "duration": 61,
    "audio_folder": "sonoraudio",
    "pdf_folder": "pdf",
    "file_mp3": "nikoru.mp3",
    "file_pdf": "nikoru.pdf",
    "downloads": 0
  },
  {
    "id": "pequenas-aventuras",
    "title": "Pequeñas Aventuras",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Urbano",
    "style_decade": "2000s",
    "ambience": "Parque",
    "mood": "Juguetón",
    "duration": 58,
    "audio_folder": "sonoraudio",
    "pdf_folder": "pdf",
    "file_mp3": "pequenas-aventuras.mp3",
    "file_pdf": "pequenas-aventuras.pdf",
    "downloads": 0
  },
  {
    "id": "royal",
    "title": "Royal",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Cinematográfico",
    "style_decade": "1940s",
    "ambience": "Salón",
    "mood": "Elegante",
    "duration": 79,
    "audio_folder": "sonoraudio",
    "pdf_folder": "pdf",
    "file_mp3": "royal.mp3",
    "file_pdf": "royal.pdf",
    "downloads": 0
  },
  {
    "id": "silvestre",
    "title": "Silvestre",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Folclórico",
    "style_decade": "1950s",
    "ambience": "Selva",
    "mood": "Libre",
    "duration": 76,
    "audio_folder": "sonoraudio",
    "pdf_folder": "pdf",
    "file_mp3": "silvestre.mp3",
    "file_pdf": "silvestre.pdf",
    "downloads": 0
  },
  {
    "id": "tonada-marabina",
    "title": "Tonada Marabina",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Folclórico",
    "style_decade": "1960s",
    "ambience": "Río",
    "mood": "Melancólico",
    "duration": 83,
    "audio_folder": "sonoraudio",
    "pdf_folder": "pdf",
    "file_mp3": "tonada-marabina.mp3",
    "file_pdf": "tonada-marabina.pdf",
    "downloads": 0
  },
  {
    "id": "vako",
    "title": "Vako",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Cinematográfico",
    "style_decade": "2020s",
    "ambience": "Vacío",
    "mood": "Minimalista",
    "duration": 65,
    "audio_folder": "sonoraudio",
    "pdf_folder": "pdf",
    "file_mp3": "vako.mp3",
    "file_pdf": "vako.pdf",
    "downloads": 0
  },
  {
    "id": "zapaticos",
    "title": "Zapaticos",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Íntimo",
    "style_decade": "1990s",
    "ambience": "Infancia",
    "mood": "Tierno",
    "duration": 60,
    "audio_folder": "sonoraudio",
    "pdf_folder": "pdf",
    "file_mp3": "zapaticos.mp3",
    "file_pdf": "zapaticos.pdf",
    "downloads": 0
  },
  {
    "id": "al-jazz",
    "title": "Al Jazz",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Jazz",
    "style_decade": "1950s",
    "ambience": "Club nocturno",
    "mood": "Relajado",
    "duration": 74,
    "audio_folder": "audiline",
    "pdf_folder": "pdf",
    "file_mp3": "al-jazz.mp3",
    "file_pdf": "al-jazz.pdf",
    "downloads": 0
  },
  {
    "id": "a-ti",
    "title": "A Ti",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Íntimo",
    "style_decade": "2020s",
    "ambience": "Hogar",
    "mood": "Tierno",
    "duration": 63,
    "audio_folder": "audiline",
    "pdf_folder": "pdf",
    "file_mp3": "a-ti.mp3",
    "file_pdf": "a-ti.pdf",
    "downloads": 0
  },
  {
    "id": "barco-de-papel",
    "title": "Barco de Papel",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Cinematográfico",
    "style_decade": "2010s",
    "ambience": "Río",
    "mood": "Nostálgico",
    "duration": 68,
    "audio_folder": "audiline",
    "pdf_folder": "pdf",
    "file_mp3": "barco-de-papel.mp3",
    "file_pdf": "barco-de-papel.pdf",
    "downloads": 0
  },
  {
    "id": "comarca",
    "title": "Comarca",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Folclórico",
    "style_decade": "1970s",
    "ambience": "Campo",
    "mood": "Tranquilo",
    "duration": 77,
    "audio_folder": "audiline",
    "pdf_folder": "pdf",
    "file_mp3": "comarca.mp3",
    "file_pdf": "comarca.pdf",
    "downloads": 0
  },
  {
    "id": "el-viaje",
    "title": "El Viaje",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Cinematográfico",
    "style_decade": "2020s",
    "ambience": "Carretera",
    "mood": "Reflexivo",
    "duration": 82,
    "audio_folder": "audiline",
    "pdf_folder": "pdf",
    "file_mp3": "el-viaje.mp3",
    "file_pdf": "el-viaje.pdf",
    "downloads": 0
  },
  {
    "id": "flagrante",
    "title": "Flagrante",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Urbano",
    "style_decade": "2000s",
    "ambience": "Ciudad",
    "mood": "Tenso",
    "duration": 66,
    "audio_folder": "audiline",
    "pdf_folder": "pdf",
    "file_mp3": "flagrante.mp3",
    "file_pdf": "flagrante.pdf",
    "downloads": 0
  },
  {
    "id": "incauto",
    "title": "Incauto",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Cinematográfico",
    "style_decade": "1990s",
    "ambience": "Tribunal",
    "mood": "Inocente",
    "duration": 70,
    "audio_folder": "audiline",
    "pdf_folder": "pdf",
    "file_mp3": "incauto.mp3",
    "file_pdf": "incauto.pdf",
    "downloads": 0
  },
  {
    "id": "joropotongo",
    "title": "Joropotongo",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Folclórico",
    "style_decade": "1960s",
    "ambience": "Llanos",
    "mood": "Festivo",
    "duration": 79,
    "audio_folder": "audiline",
    "pdf_folder": "pdf",
    "file_mp3": "joropotongo.mp3",
    "file_pdf": "joropotongo.pdf",
    "downloads": 0
  },
  {
    "id": "la-labor",
    "title": "La Labor",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Íntimo",
    "style_decade": "2020s",
    "ambience": "Taller",
    "mood": "Dedicado",
    "duration": 65,
    "audio_folder": "audiline",
    "pdf_folder": "pdf",
    "file_mp3": "la-labor.mp3",
    "file_pdf": "la-labor.pdf",
    "downloads": 0
  },
  {
    "id": "los-compadres",
    "title": "Los Compadres",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Folclórico",
    "style_decade": "1980s",
    "ambience": "Patio",
    "mood": "Amistoso",
    "duration": 73,
    "audio_folder": "audiline",
    "pdf_folder": "pdf",
    "file_mp3": "los-compadres.mp3",
    "file_pdf": "los-compadres.pdf",
    "downloads": 0
  },
  {
    "id": "luna",
    "title": "Luna",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Íntimo",
    "style_decade": "2020s",
    "ambience": "Noche",
    "mood": "Melancólico",
    "duration": 61,
    "audio_folder": "audiline",
    "pdf_folder": "pdf",
    "file_mp3": "luna.mp3",
    "file_pdf": "luna.pdf",
    "downloads": 0
  },
  {
    "id": "travesia",
    "title": "Travesía",
    "composer": "Carlos Reyes (CERT)",
    "composer_id": "carlos-reyes-cert",
    "composer_paypal": "certproducciones@gmail.com",
    "style": "Cinematográfico",
    "style_decade": "2020s",
    "ambience": "Mar",
    "mood": "Épico",
    "duration": 85,
    "audio_folder": "audiline",
    "pdf_folder": "pdf",
    "file_mp3": "travesia.mp3",
    "file_pdf": "travesia.pdf",
    "downloads": 0
  }
];